name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install libtins dependency
      run: sudo apt-get install libpcap-dev libssl-dev cmake 
    - name: install libtins 
      run: git clone https://github.com/mfontanini/libtins.git && cd libtins && mkdir build && cd build && cmake .. && \
            make && make install && ldconfig
